# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/CAB/TSN/H3/H3.srcs/sources_1/bd/h2_blockDesign/ip/h2_blockDesign_auto_pc_0/h2_blockDesign_auto_pc_0.xci
# IP: The module: 'h2_blockDesign_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/CAB/TSN/H3/H3.srcs/sources_1/bd/h2_blockDesign/ip/h2_blockDesign_auto_pc_0/h2_blockDesign_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'h2_blockDesign_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/CAB/TSN/H3/H3.srcs/sources_1/bd/h2_blockDesign/ip/h2_blockDesign_auto_pc_0/h2_blockDesign_auto_pc_0.xci
# IP: The module: 'h2_blockDesign_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/CAB/TSN/H3/H3.srcs/sources_1/bd/h2_blockDesign/ip/h2_blockDesign_auto_pc_0/h2_blockDesign_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'h2_blockDesign_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
