# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z010iclg225-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir e:/cab/tsn/audio_ip/ip_repo/edit_audio_ip_v1_1.cache/wt [current_project]
set_property parent.project_path e:/cab/tsn/audio_ip/ip_repo/edit_audio_ip_v1_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths {
  e:/CAB/TSN/audio_ip/ip_repo/audio_ip_1.1
  e:/CAB/TSN/audio_ip/audio_ip_1.0
  e:/CAB/TSN/audio_ip/ip_repo/audio_ip_1.0
} [current_project]
update_ip_catalog
set_property ip_output_repo e:/cab/tsn/audio_ip/ip_repo/edit_audio_ip_v1_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  e:/CAB/TSN/audio_ip/ip_repo/audio_ip_1.1/src/ADAU1761_interface.vhd
  e:/CAB/TSN/audio_ip/ip_repo/audio_ip_1.1/src/adau1761_configuraiton_data.vhd
  e:/CAB/TSN/audio_ip/ip_repo/audio_ip_1.1/src/adau1761_izedboard.vhd
  e:/CAB/TSN/audio_ip/ip_repo/audio_ip_1.1/src/dsp_block.vhd
  e:/CAB/TSN/audio_ip/ip_repo/audio_ip_1.1/src/i2c.vhd
  e:/CAB/TSN/audio_ip/ip_repo/audio_ip_1.1/src/i2s_data_interface.vhd
  e:/CAB/TSN/audio_ip/ip_repo/audio_ip_1.1/src/i3c2.vhd
  e:/CAB/TSN/audio_ip/ip_repo/audio_ip_1.1/src/low_pass_moving_sum.vhd
}
read_vhdl -library "" {
  e:/CAB/TSN/audio_ip/ip_repo/audio_ip_1.1/hdl/audio_ip_v1_1_S00_AXI.vhd
  e:/CAB/TSN/audio_ip/ip_repo/audio_ip_1.1/hdl/audio_ip_v1_1.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top audio_ip_v1_1 -part xc7z010iclg225-1L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef audio_ip_v1_1.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file audio_ip_v1_1_utilization_synth.rpt -pb audio_ip_v1_1_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
