# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/constraints.xdc

# Block Designs: bd/h2_blockDesign/h2_blockDesign.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==h2_blockDesign || ORIG_REF_NAME==h2_blockDesign} -quiet] -quiet

# IP: bd/h2_blockDesign/ip/h2_blockDesign_processing_system7_0_0/h2_blockDesign_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==h2_blockDesign_processing_system7_0_0 || ORIG_REF_NAME==h2_blockDesign_processing_system7_0_0} -quiet] -quiet

# IP: bd/h2_blockDesign/ip/h2_blockDesign_audio_ip_0_0/h2_blockDesign_audio_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==h2_blockDesign_audio_ip_0_0 || ORIG_REF_NAME==h2_blockDesign_audio_ip_0_0} -quiet] -quiet

# IP: bd/h2_blockDesign/ip/h2_blockDesign_axi_gpio_0_0/h2_blockDesign_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==h2_blockDesign_axi_gpio_0_0 || ORIG_REF_NAME==h2_blockDesign_axi_gpio_0_0} -quiet] -quiet

# IP: bd/h2_blockDesign/ip/h2_blockDesign_xbar_0/h2_blockDesign_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==h2_blockDesign_xbar_0 || ORIG_REF_NAME==h2_blockDesign_xbar_0} -quiet] -quiet

# IP: bd/h2_blockDesign/ip/h2_blockDesign_ps7_0_axi_periph_0/h2_blockDesign_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==h2_blockDesign_ps7_0_axi_periph_0 || ORIG_REF_NAME==h2_blockDesign_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/h2_blockDesign/ip/h2_blockDesign_rst_ps7_0_100M_0/h2_blockDesign_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==h2_blockDesign_rst_ps7_0_100M_0 || ORIG_REF_NAME==h2_blockDesign_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/h2_blockDesign/ip/h2_blockDesign_auto_pc_0/h2_blockDesign_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==h2_blockDesign_auto_pc_0 || ORIG_REF_NAME==h2_blockDesign_auto_pc_0} -quiet] -quiet

# XDC: bd/h2_blockDesign/h2_blockDesign_ooc.xdc
